### ISSUE TITLE
cannot import

### ISSUE THREAD

**Issue by stevenli11** [deepomicslab/GNNFrame#1]
I appreciate this job, but I have a problem. The following error occurred when I executed the code:
test.py:
```
from GCNFrame import Biodata, GCNmodel
ImportError: cannot import name 'encode_seq' from partially initialized module 'GCNFrame' (most likely due to a circular import)(D:\tool-study\Anaconda3\envs\gcn1\lib\site-packages\GCNFrame\__init__.py)
```

__init__.py:
```
from GCNFrame.Biodata import BipartiteData, GraphDataset, Biodata
from GCNFrame.GCNmodel import model, train, evaluation, test
```
What am I doing wrong? Looking forward to your reply, thank you.

**Comment by wangruohan111** [comment]
Hi,

Could you please download the package from the GitHub repository and recompile it with "python setup.py build_ext --inplace" as introduced in the README file?

This problem seems to be caused by compiling. I have compiled the CPython script in Linux and MACOS systems, and it needs to be recompiled if you use other systems.

Please let me know if there are any problems.

**Comment by Leven1113** [comment]
> 你好，
> 
> 您能否从 GitHub 存储库下载该软件包并使用 README 文件中介绍的“python setup.py build_ext --inplace”重新编译它？
> 
> 这个问题好像是编译引起的。CPython脚本我在Linux和MACOS系统都编译过，如果使用其他系统需要重新编译。
> 
> 如果有任何问题，请告诉我。

**Comment by Leven1113** [comment]
Thank you for your reply. I use the Windows system, and I have executed this compilation command:
`python setup.py build_ext --inplace`
This file "encode_seq.cp38-win_amd64.pyd" was generated.

But now there is another problem. In "encode_seq.c" this file, here on line 29, I use MinGW64. 
```
#include "Python.h"
Error: #include error detected. Please update includePath. Waveform curves have been disabled for this translation unit. Unable to open source file "Python. h" C/C++(1696).
```

**Comment by stevenli11** [comment]
I solved the above problem. On line 291:
enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
Error: Divide by zero C/C++(39)

**Comment by stevenli11** [comment]
Maybe the second problem is my vscode settings. After I changed the pycharm, it was OK.
The problem is still the first one:
`cannot import name 'encode_seq' from partially initialized module 'GCNFrame' (most likely due to a circular import)(D:\tool-study\Anaconda3\envs\gcn1\lib\site-packages\GCNFrame\__init__.py)
`

**Comment by wangruohan111** [comment]
Could you please uninstall the pip package using "pip uninstall GCNFrame", so that you can use the package from GitHub with your newly compiled program? It seems that you still use the package from PyPI.

**Comment by stevenli11** [comment]
> Could you please uninstall the pip package using "pip install GCNFrame", so that you can use the package from GitHub with your newly compiled program? It seems that you still use the package from PyPI.
Thank you for your reply. Yes, I still use PyPI's package. I'll try again.
`gcnframe                  0.0.4                    pypi_0    pypi`

**Comment by stevenli11** [comment]
I've solved it, it's running. Thanks a lot.

**Comment by wangruohan111** [comment]
Good! I am going to close this issue. Please feel free to open another if there are other problems.
