### ISSUE TITLE
Can I use very large k (kmer length) and d (distance)

### ISSUE THREAD

**Issue by dawnmy** [deepomicslab/GNNFrame#3]
Thank you developing this interesting approach for sequence representation. In your example, you suggest to use k=3 and d=3. However such small k and d, could not deliver high specificity for complex sequence classification especially when similar sequences with different labels are present. Can I use a k of 9 and d of 9? What will happen if I use these large k and d?

**Comment by wangruohan111** [comment]
Hi, for large d, the framework is able to consider large distance (d=4 for distance 0-4, d=5 for distance 0-8, d=6 for distance 0-16, d=7 for distance 0-32, and d=8 for distance 0-64). For large k, such as 9, it may cause a memory error.
