### ISSUE TITLE
Doubts about GCNFrame installation

### ISSUE THREAD

**Issue by z626093820** [deepomicslab/GNNFrame#5]
When I install GCNFrame on the Windos platform, the following error occurs

(torch1.7) E:\下载\GCNFrame\GCNFrame>python
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 15:53:35) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from GCNFrame import Biodata, GCNmodel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\miniconda3\envs\torch1.7\lib\site-packages\GCNFrame\__init__.py", line 1, in <module>
    from GCNFrame.Biodata import BipartiteData, GraphDataset, Biodata
  File "D:\miniconda3\envs\torch1.7\lib\site-packages\GCNFrame\Biodata.py", line 11, in <module>
    from GCNFrame import encode_seq
ImportError: cannot import name 'encode_seq' from partially initialized module 'GCNFrame' (most likely due to a circular import) (D:\miniconda3\envs\torch1.7\lib\site-packages\GCNFrame\__init__.py)

How can I fix this please, thanks in advance!

**Comment by wangruohan111** [comment]
Please use the "python setup.py build_ext --inplace" command under GCNFrame/GCNFrame/ dictionary.
