### ISSUE TITLE
安装配置时的一些困扰

### ISSUE THREAD

**Issue by MaoFuyou** [deepomicslab/GNNFrame#6]
![image](https://github.com/deepomicslab/GCNFrame/assets/93516514/23775072-5712-4653-97ed-71ec98a65e07)
我想知道这个报错是怎么回事呢？

**Comment by wangruohan111** [comment]
This is a warning caused by old Numpy versions. I think it should not cause an error in the program, but you may try to avoid it according to these suggestions: https://stackoverflow.com/questions/52749662/using-deprecated-numpy-api.

**Comment by MaoFuyou** [comment]
您好 这个问题解决了：但是我遇到了新的问题：
![image](https://github.com/deepomicslab/GCNFrame/assets/93516514/487ec2a7-7d65-4a26-94c6-f851303aa44b)
这是我的GPU版本；
![image](https://github.com/deepomicslab/GCNFrame/assets/93516514/f98ab9ff-cb27-4d6f-bd11-8d0885a6dfa6)
我在对数据进行encode时候耗费了好长的时间，这个数据的规模和您的样例里面是一样的 但是规模比您的那个小，想问一下为啥编码这么慢？

**Comment by MaoFuyou** [comment]
<img width="1079" alt="1501b1eb4ae6a510f6eedb78d5a9371" src="https://github.com/deepomicslab/GCNFrame/assets/93516514/f4ac5708-c45f-4627-9db8-56f4497983f8">

**Comment by wangruohan111** [comment]
The running time of encoding increases linearly with the number of sequences in your data.
