### ISSUE TITLE
about encode_seq

### ISSUE THREAD

**Issue by Dowson0** [deepomicslab/GNNFrame#8]
当我处理dna数据时，出现问题。希望您能帮我解答一下，谢谢
![image](https://github.com/user-attachments/assets/ad1454ec-ea70-4153-9651-63130fe5a518)

**Comment by wangruohan111** [comment]
你好，这是因为cython版本不一致导致的，我们测试的cython版本是0.29，请试一下这个版本。

如果有其他问题请再联系我。

**Comment by Dowson0** [comment]
好的，谢谢您。问题已经解决
